#!/usr/bin/env bash

set -euo pipefail

grep -l 'func main' ./*/*.go | grep -v generics-experiments | while read -r file; do
  dir=${file%/*}
  dir=${dir#./}
  echo "$dir"
  if [[ -x $dir/build ]]; then
    (cd "$dir" && ./build)
  else
    (cd "$dir" && go build)
  fi
done
