#!/usr/bin/env bash

set -euo pipefail

for file in *.go; do
  name=${file%.go}
  printf "\n%s:\n" "${name}"
  mkdir "${name}"
  git mv "$file" "${name}/"
  echo "${name}" >>"${name}/.gitignore"
  git add "${name}/.gitignore"
done
